name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      fileName:
        description: 'File Name'
        required: true
      content:
        description: 'File Content'
        required: true
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debugging inputs
      run: |
        FILE_NAME="${{ github.event.inputs.fileName }}"
        CONTENT="${{ github.event.inputs.content }}"
        echo "File Name: $FILE_NAME"
        echo "Content Length: ${#CONTENT}"

    - name: Upload files to GitHub
      run: |
        echo "Uploading file to Video folder"
        content=$(echo "${{ github.event.inputs.content }}" | base64)

        # 檢查檔案名稱是否存在
        if [[ -z "${{ github.event.inputs.fileName }}" ]]; then
          echo "File name is missing!"
          exit 1
        fi

        echo "Encoded Content Length: ${#content}"

        curl -X PUT \
          -H "Authorization: token ${{ secrets.UPLOAD_TOKEN }}" \  # 使用你設定的 GitHub Token
          -H "Content-Type: application/json" \
          -d '{
            "message": "Uploading file to Video folder",
            "content": "'"$content"'"
          }' \
          "https://api.github.com/repos/DongShanSalmon/DongShanSalmon.github.io/contents/Video/${{ github.event.inputs.fileName }}"
