name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      fileName:
        description: 'File Name'
        required: true
      content:
        description: 'File Content'
        required: true
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set variables
      run: |
        echo "FILE_NAME=${{ github.event.inputs.fileName }}" >> $GITHUB_ENV
        echo "CONTENT=${{ github.event.inputs.content }}" >> $GITHUB_ENV

    - name: Debugging inputs
      run: |
        echo "File Name: $FILE_NAME"
        echo "Content Length: ${#CONTENT}"

    - name: Upload files to GitHub
      run: |
        echo "Uploading file to Video folder"
        content=$(echo "$CONTENT" | base64)

        # 檢查檔案名稱是否存在
        if [[ -z "$FILE_NAME" ]]; then
          echo "File name is missing!"
          exit 1
        fi

        echo "Encoded Content Length: ${#content}"

        curl -X PUT \
          -H "Authorization: token ${{ secrets.UPLOAD_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "message": "Uploading file to Video folder",
            "content": "'"$content"'"
          }' \
          "https://api.github.com/repos/DongShanSalmon/DongShanSalmon.github.io/contents/Video/$FILE_NAME"
