name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # 允許手動觸發工作流
    inputs:
      fileName:  # 檔案名稱輸入
        description: 'File Name'
        required: true
      content:  # 檔案內容輸入
        description: 'File Content'
        required: true
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload files to GitHub
      run: |
        echo "Uploading file to Video folder"
        # 將輸入的檔案名稱和內容保存為環境變數
        echo "${{ github.event.inputs.fileName }}" > fileName.txt
        echo "${{ github.event.inputs.content }}" > content.txt

        # 使用 curl 上傳檔案
        curl -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "message": "Uploading file to Video folder",
            "content": "'$(cat content.txt | base64)'"
          }' \
          "https://api.github.com/repos/DongShanSalmon/DongShanSalmon.github.io/contents/Video/${{ github.event.inputs.fileName }}"
