name: Upload File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Base64-encoded file content'
        required: true
      path:
        description: 'Path for the file (e.g., "file/YOUR_IMAGE.jpg")'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload file using GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}  # 確保這裡使用的是你的 Secret
        run: |
          echo "Uploading file..."
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"message": "Upload file", "content": "${{ github.event.inputs.file }}"}' \
          "https://api.github.com/repos/DongShanSalmon/DongShanSalmon.github.io/contents/${{ github.event.inputs.path }}"
